"""add severity to tasks

Revision ID: 535dea04aa91
Revises: ea55724616d2
Create Date: 2025-12-05 18:27:12.588267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '535dea04aa91'
down_revision: Union[str, Sequence[str], None] = 'ea55724616d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    taskseverity = sa.Enum('low', 'medium', 'high', 'critical', name='taskseverity')
    taskseverity.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('severity', taskseverity, server_default='low', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'severity')
    # ### end Alembic commands ###
